spring:
  activemq:
    broker-url: tcp://116.62.38.97:61616
    user: admin
    password: admin
  jms:
    pub-sub-domain: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/taobao?useSSL=false
    username: root
    password: root
  redis:
    host: 116.62.38.97
    port: 63799
    password: root